### ISSUE TITLE
multer opts

### ISSUE THREAD

**Issue by oreporan** [lukeautry/tsoa#1111]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [X] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Have the ability to pass [multer opts](https://github.com/expressjs/multer#multeropts)

## Current Behavior

Currently I'm not able to pass any of the [multer opts](https://github.com/expressjs/multer#multeropts). 
In my current use case, requests are failing on "Field value too long" - which can be handled by increasing [multer limits](https://github.com/expressjs/multer/issues/436)

My code looks like this:
```ts
  public async myFunc(
        @Request() request: ExpressRequest,
        @UploadedFile() logo: Express.Multer.File,
        @FormField('top') topRaw: Top,
        @FormField('left') leftRaw: Left
    ): Promise<void> {
       
        ...
    }
```

## Possible Solution

```ts
@UploadedFile(opts) logo: Express.Multer.File
```

## Steps to Reproduce

1. 2. 3. 4.

## Context (Environment)

Version of the library: 3.8.0
Version of NodeJS: 14

- Confirm you were using yarn not npm: [X]

**Comment by WoH** [comment]
Would you be interested in sending a PR for that?

**Comment by cma-skedulo** [comment]
@WoH Should we manage multer config inside tsoa.json instead of using decorator?
That way can have single multer instant for all controllers methods.

**Comment by WoH** [comment]
The reason why I didn't propose the tsoa.json approach was my fear of only delaying the request for 
a) supporting the `storage` option
b) supporting different options per Endpoint

In light of #1144 at least a) should no longer be an issue, but I'd like to have that tested if possible.

**Comment by cma-skedulo** [comment]
I don't think #1144 will help to resolve the multer's storage option as we still need to generate the storage's implementation back to routes.ts using handlebar.

Maybe for storage option, we can do something similar to authenticationModule and let the routes import it instead of generate the middleware code in routes.ts. 
Like a uploadFileModule and export a factory for upload middleware, that way end user can pick different library instead of multer if they want to.

**Comment by WoH** [comment]
> I don't think #1144 will help to resolve the multer's storage option as we still need to generate/write the storage's implementation back to routes.ts using handlebar.

Maybe I wasn't not precise enough. We have the option to let the user define a function, we still need to get it into the template, that's correct.

> Maybe for storage option, we can do something similar to authenticationModule and let the routes import it instead of generate the middleware code in routes.ts. 
> Like a uploadFileModule and export a factory for upload middleware, that way end user can pick different library instead of multer if they want to.

Considering b) I'm not sure if that would solve the problems for long, but it's an option.

**Comment by cma-skedulo** [comment]
Let me pull something for christmas for the uploadModule

In the mean time, should we update the document at https://tsoa-community.github.io/docs/file-upload.html#using-the-uploadedfile-uploadedfiles-decorator?

> Note, that using the decorator defaults to saving on the disk with a default file location set to the OS's temp folder.

https://github.com/expressjs/multer/blob/4f4326a6687635411a69d70f954f48abb4bce58a/index.js#L17

TSOA template's multer implementation is only `multer()` so it will be using MemoryStorage instead of DiskStorage with the default os.tmpdir folder

**Comment by WoH** [comment]
We can fix this in the 4.x releases, which are currently in alpha, with a breaking change, but important catch.

**Comment by mayankchutani** [comment]
Is there a good example somewhere for a multipart file upload controller definition?

Also, the documentation says `Express.multer.file`. What is `Express` here?

**Comment by couimet** [comment]
> As I faced the same issue in the past and worked around it by using my own `routeGeneration` template (which is obviously not the best solution), I would love to send a PR.

@FelixGraf I'm fully aware this comment is pretty old, but would you still happen to have the code that uses the template you referred to available as a reference ?

Thanks !
