### ISSUE TITLE
@Response creates wrong swagger code

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#119]
Hello,

after investigating an issue, if found out what's going wrong. There is a swagger validation error when using swagger-parser.

In one of our example we have:

`    @Response<ErrorResponseModel>('Unexpected error')`

This produces the follwing malformed code in swagger.json

```
"responses": {
	"200": {
		"description": "Ok",
		"schema": {
			"$ref": "#/definitions/UserResponseModel"
		}
	},
	"Unexpected error": {
		"description": "",
		"schema": {
			"$ref": "#/definitions/ErrorResponseModel"
		}
	}
},
```	

It should also create a 200 - as no status number is given - and 200 is the default:

```
"responses": {
	"200": {
		"description": "Ok",
		"schema": {
			"$ref": "#/definitions/UserResponseModel"
		}
	},
	"200": {
		"description": "Unexpected error",
		"schema": {
			"$ref": "#/definitions/ErrorResponseModel"
		}
	}
},
```

Everething works fine when using this:

`@Response<ErrorResponseModel>(400, 'Unexpected error')`

**Comment by dgreene1** [comment]
I think the fix for this would be:

1. tsoa should validate that the first parameter of `@Response` is a valid http status code.
2. the status code should not be allowed to be `200` or "200"` since that return type is already defined by the return of the route function.

If we're able to validate those two concerns, then it would prevent someone from creating the duplicates that you describe above.

If anyone would like an easy first issue, this is one.

**Comment by WoH** [comment]
Valid Responses according to OpenAPI 3 are listed here: https://github.com/OAI/OpenAPI-Specification/blob/v3.1.0-dev/versions/3.1.0.md#responses-object

I'd accept a PR that restricts this to: HTTP Status Code numbers (see [here](https://tsoa-community.github.io/reference/modules/_tsoa_runtime.html#httpstatuscodeliteral-1)),  their stringified counterparts, "1XX", "2XX", "3XX", "4XX", and 5XX and "default".
