### ISSUE TITLE
Would it be compatible with such frameworks as routing-controllers or nest in the future? Thanks!

### ISSUE THREAD

**Issue by idchlife** [lukeautry/tsoa#137]

**Comment by dgreene1** [comment]
Personally, I think the beauty of `tsoa` is that it's compatible with `express`, `koa, `hapi`, and more (via custom handlebars templates), so I think tsoa is a much better choice than "all-in" frameworks like NestJS.

Either way, this issue is neither a feature request, a bug, or a usage question. If you have a specific question about how to use tsoa with NestJS, please open up a new issue with more information.

Thank you both for the enthusiasm for tsoa. It's pretty awesome project. :)
