### ISSUE TITLE
Issue with @Security

### ISSUE THREAD

**Issue by egandro** [lukeautry/tsoa#138]
It seams that the Securty decorator can be set to a controller - but the swagger files don't honor that for every route.

**Comment by dgreene1** [comment]
Closing since this is old and may no longer be reproduce-able after https://github.com/lukeautry/tsoa/commit/f7ae88d9ed540b6978af85798f223657210503ec was completed. If it is reproduce-able still, can someone please provide some example code or an example repo? In the meantime, we'll close this for housekeeping purposes.
