### ISSUE TITLE
Ask, How to use Validator tag, between JSDoc or Decorator

### ISSUE THREAD

**Issue by isman-usoh** [lukeautry/tsoa#143]
1. Validator tag by JSDoc
ex.
```ts
interface Model {
  /**
   * @min 10
   * @max 100
   */
   numberValue: number;
} 
````

2. Validator tag by Decorator, 
But decorator not work interface model
ex
```ts
class Model {
   @Min(10)
   @Max(100)
   numberValue: number;
} 
````

**Comment by AmazingTurtle** [comment]
What is the issue here? Please clarify.

**Comment by dgreene1** [comment]
Closing this since it’s unclear what the question is and also because it’s very old. The best I can tell, the answer is to use the JSDoc annotations.

There are examples of the JSDoc validators at these two links:
https://github.com/lukeautry/tsoa/blob/121565d0facbe86d1793612cab0a8df666e5d6f9/tests/fixtures/testModel.ts#L236
and here:
https://github.com/lukeautry/tsoa/blob/41dcf54ec2bfac4a301328f9a602718e4b2e3674/tests/fixtures/controllers/getController.ts#L83
