### ISSUE TITLE
How to populate spec's reusable parameters?

### ISSUE THREAD

**Issue by dvishniakov** [lukeautry/tsoa#146]
According to Swagger 2.0 spec there should be possible to reuse parameters.
Here the package knows about it: [swagger.ts](https://github.com/lukeautry/tsoa/blob/524db88d7da8beadb8b717425531bd659d6a0110/src/swagger/swagger.ts#L34)
But I don't see any code which fills it: [specGenerator.ts](https://github.com/lukeautry/tsoa/blob/65a2cf9650b2a0cc24d476dce95505996e00c63e/src/swagger/specGenerator.ts#L8)
Is it a missing feature or do I miss something?

**Comment by dgreene1** [comment]
Can you clarify what you mean by “reuse parameters?”

And since this question is 2 years old, I suspect that you might not recall what you were trying to accomplish. So I’ll close the issue in the meantime. If we can still answer your question, we can reopen the issue.

I apologize for the delay in answering your question— we have new and additional maintainers now to provide support.
