### ISSUE TITLE
SubType support

### ISSUE THREAD

**Issue by areijngoudt** [lukeautry/tsoa#169]
Please add support for sub types as described in the Swagger specs.
Btw: we love using this great tool!

**Comment by egandro** [comment]
Can you please give us an example - including what you expect in Typescript and what should be created in swagger?

**Comment by AmazingTurtle** [comment]
I'm pretty sure this is what he meant (Union Types):

```
type MobileNumber = {
   type: 'mobile';
   mobile: number;
}
type PhoneNumber = {
   type: 'phone';
   phone: number;
   somethingThatDoesOnlyExistHere: any;
}
export class ModelThatIsBeingUsedByTsoa {
   number: MobileNumber | PhoneNumber;
}
```

Because this is what fails for me.
More specifically

```
Generate swagger error.
 TypeError: Cannot read property 'text' of undefined
    at ***\node_modules\tsoa\dist\metadataGeneration\resolveType.js:254:79
    at Array.map (<anonymous>)
    at getLiteralType (***\node_modules\tsoa\dist\metadataGeneration\resolveType.js:254:27)
```

@lukeautry are you familiar? Is this kind of union typing supported? If not, will it be?

**Comment by dgreene1** [comment]
If it is a request for union types, then we can track it in https://github.com/lukeautry/tsoa/issues/393. Closing as a duplicate.

**Comment by dgreene1** [comment]
@areijngoudt / @AmazingTurtle / @egandro, I'm happy to report that the we added our first draft of unions and intersections in v2.4.11. Please consider upgrading to it and let us know how it works for you. :) Please note: you must have config.swagger.specVersion set to 3 for this to work since `oneOf` and `allOf` are not supported in Swagger (but they are in OpenAPI 3.0).
