### ISSUE TITLE
"headers" property for responses is not generated in swagger

### ISSUE THREAD

**Issue by ThomasKruegl** [lukeautry/tsoa#170]
Hi,

we are trying to use tsoa to generate a swagger specification for our API. We are running into several issues, here is one of them.
There are other issues here on github regarding the use of custom headers in responses. From what i have understood it is now possible to set custom headers, and this works fine for the generated routes.
But for the generated swagger, there is simply no way of getting the headers property created for responses right?

kind regards,
Thomas

**Comment by dgreene1** [comment]
I believe the answer is to use the `@Request` parameter decorator. I’ve added more information to the readme on how to use it. Once you have that (and have set the type to be either `Express.Request` or `Koa.Request`), you have the full ability to set the header in the same that you would have with pure Express or Koa.

As for declaring it in Swagger... I actually don’t know (I just recently joined as a maintainer).

So I’ll mark this issue as [help wanted] so that maybe someone can either:
* tell us if there is a way to do this in tsoa
* or add that functionality

My apologies for the delay in answering. We have new, additional maintainers who will be adding more support in the future.

**Comment by ThomasKruegl** [comment]
Currently i am working in a completely different environment, and don't have time to follow up on this. Just saying so you know i won't be able to test or do anything here.
But thanks for picking this up anyway :)

**Comment by sundowndev** [comment]
Up, this is still relevant today. `this.setHeader` works for generated routes but doesn't write in the specs. So for now it's impossible to change `application/json` response content type in the docs.

```ts
const stat: fs.Stats = await fs.promises.stat(filePath);

this.setStatus(200);
this.setHeader('Content-Type', 'application/pdf');
this.setHeader('Content-Length', stat.size.toString());
```

![image](https://user-images.githubusercontent.com/16480203/94701712-40cd0b00-033d-11eb-853d-d687b9a5bf64.png)

**Comment by WoH** [comment]
> Up, this is still relevant today. `this.setHeader` works for generated routes but doesn't write in the specs. So, from what I understand, for now it's impossible to change `application/json` response content type in the docs.
> 
> ```ts
> const stat: fs.Stats = await fs.promises.stat(filePath);
> 
> this.setStatus(200);
> this.setHeader('Content-Type', 'application/pdf');
> this.setHeader('Content-Length', stat.size.toString());
> ```
> 
> ![image](https://user-images.githubusercontent.com/16480203/94701712-40cd0b00-033d-11eb-853d-d687b9a5bf64.png)

We can't guess how you set the headers at runtime. Closing this in favor of #770
