### ISSUE TITLE
Suggestion @User decorator

### ISSUE THREAD

**Issue by MatthiasKunnen** [lukeautry/tsoa#274]
Currently, to get the user in the controllers, you need to add `@Request request` and then extract the user using `request.user`. I propose to add a `@User user` that would do this step for you. 
If this is something that would be accepted I could make a PR sometime this month.

**Comment by endor** [comment]
Hm, I think I saw something about this before, in some other PR or something and spoke out against it, because I thought the object coming out of the authentication method is not necessarily a user. But looking at the code that already exists and what most people are doing, it seems to be a user most of the time, so I think such a decorator could make sense. 

What I'm doing in the project I'm working on is extending the express `Request` and adding a `Token` object on it, that I can then access and have typed. If we use `@User`, that would probably mean having an `any` there?

Any thoughts @lukeautry @jpramondon?

**Comment by jpramondon** [comment]
I agree with the first part. What is out of the auth part (whatever declination of a principal) of a request is not always a user. It could fairly also depends on auth mechanism. One has got to know exactly what to expect out of a `request.user`.

That said if most expect what looks like a user, then why not have a such decorator ? (with proper warnings documented in case the outcome cannot be a user).

The thing with typings is that either you'd end up having to define what comes out of the decorator more precisely (and certainly create a whole bunch of interfaces to define the possible outcomes and their relationships - with the question tsoa being the place for that), or use an `any` (which I am personally not very fond of).

**Comment by lukeautry** [comment]
I'm not a big fan of adding User to tsoa, just because it's highly domain specific, and a "user" could be shaped very differently depending on the domain. I think tsoa's job should be to support common application flows via documentation, examples, and custom templates.

In our case, we just use a custom template that is largely taken from the canonical express template. The authenticateMiddleware:

```
if (!success) {
          success = true;
          responded++;
          request['user'] = user;
          next();
}
```

The user is injected into the request using the return value of the custom authentication module:

```
export interface IRequestContext extends express.Request {
  user: User;
}

export const expressAuthentication = async (request: IRequestContext, securityName: string, _scopes?: string[]): Promise<User> => {
  ...
};
```

Controllers user something like this:
```
@Delete('accounts/{id}')
@Security('admin')
@Tags('Admin')
public async deleteAccount(@Request() context: IRequestContext, id: number) {
    await new AccountService().deleteAccount(context.user, id);
}
```

**Comment by MatthiasKunnen** [comment]
Personally, I do not like to have an extra step every time I need to access the user object. I noticed that in all functions in which I require access to the user I do: 
```TypeScript
method(@Request() request: Request) {
    const user =  request.user;
    // ....
}
```

I see the `@User` as a shortcut to `request.user`.

Is there a big difference between `request.user` and `user` or am I misunderstanding your explanation? Are you pointing to the possibility of the authentication middleware to do: `request['banana'] = banana;` and that an `@User()` decorator would consequently not work?

Perhaps this decorator could be available for simple use cases such as mine but be clearly documented as _one of_ the ways to achieve authentication.

**Comment by dgreene1** [comment]
Since this issue not preventing anyone from using tsoa and because the key maintainer already clarified his views on this, I'm going to close the issue.

I'm closing for housekeeping purposes. In order for tsoa to get increased adoption, it's important that we have a smaller number of open issues and PRs.
