### ISSUE TITLE
@Body primitive body not generated correctly

### ISSUE THREAD

**Issue by redlock** [lukeautry/tsoa#290]
When using a @Body decorator for an argument like so:

```ts
	@Put("{id}")
	async saveScript(id: number, @Body() body: string) {
``` 

tsoa generates the following:
```json

{
	"in": "body",
	"name": "body",
	"required": true,
	"type": "string"
}

```

This is incorrect according to Swagger specs:

https://swagger.io/docs/specification/2-0/describing-request-body/

it should look like this:

```json

{
	"in": "body",
	"name": "body",
	"required": true,
	"schema": {
              "type": "string"
        }
}

```

Thanks

**Comment by dgreene1** [comment]
Good catch. This seems to be partially a user error since an object is the only valid type a body can have (unless tsoa were to pass the raw string before it sends it to JSON.parse). That being said, tsoa shouldn't necessarily allow for this configuration. So I'll add the help wanted flag since this would be easy to validate during route generation.

**Comment by dgreene1** [comment]
Hi @redlock, I thought about this a while, and I even tried to implement the feature. It turns out that (a) it's more complicated than I thought and (b) it's actually pretty uncommon for a body to be just a string.

Please read my full explanation in this related issue: https://github.com/lukeautry/tsoa/issues/95#issuecomment-533628700
