### ISSUE TITLE
Multiple matching module declarations found for ${leftmostName}; please make module declarations unique

### ISSUE THREAD

**Issue by linxiaowu66** [lukeautry/tsoa#333]
Hi  guys,
  
   Can the tsoa to support multiple same module definition ?

**Comment by dgreene1** [comment]
This is answered in the readme: https://github.com/lukeautry/tsoa#dealing-with-duplicate-model-names

**Comment by endor** [comment]
I would like to reopen this, because I'm not sure this answers the question.

I'm currently working on a service where we would like to use Stripe. I know that tsoa suggests creating copies of the interfaces defined in external libraries, but if I wanted to still use a type defined in Stripe as a property defined in my own interface, I end up with:

```
 Error: Multiple matching module declarations found for Stripe; please make module declarations unique.
```

And I think it is, because Stripe defines their API like so:

```
declare module 'stripe' {
  namespace Stripe {
    interface Account {
declare module 'stripe' {
  namespace Stripe {
    interface Balance {
```

Is there a reason tsoa doesn't support reopening modules or is it just something that hasn't been done yet or am I just using it incorrectly?

**Comment by endor** [comment]
ping @dgreene1 @WoH

**Comment by WoH** [comment]
It's because we are still using the resolution approach luke wrote back when ts didn't have APIs for that I think.
Basically, we iterate over all the statements to find a matching node according to what tsoa considers matching, which is not correct in these cases.
I thought about rewriting that using the algorithm i.e. the language server uses to "Jump to declaration", but unless someone has time to actually write this, we can't do this yet.

**Comment by endor** [comment]
This sounds like a big task, even though it's probably the right thing to do. I am wondering though, if it would also make sense or even be possible to try and take a smaller step and search those multiple module declarations for the member we're looking for.

**Comment by WoH** [comment]
Since TS exposes `getDeclarations()` and `.valueDeclaration`, it's probably less work than supporting another hack on top of our custom implementation.
