### ISSUE TITLE
Add warning to default templates

### ISSUE THREAD

**Issue by aktary** [lukeautry/tsoa#344]
Add a warning comment in the default templates so developers on the team who don't know about tsoa don't try to edit the generated files directly.

**Comment by dgreene1** [comment]
@aktary I just released 2.4.5 which has this change. Thank your for being a member of our community. I'd love it if more people were using `tsoa` since it's such a helpful library. If you wouldn't mind, please share it with people on twitter, reddit, or [dev.to](https://dev.to)?

Also, there were a bunch of other enhancements that went out in previous version 2.4.4. Check those out in: https://github.com/lukeautry/tsoa/releases
