### ISSUE TITLE
"Create Controllers" section of README has some faulty code

### ISSUE THREAD

**Issue by MageCity** [lukeautry/tsoa#349]
Was working on a PR to fix it but there's enough that I'm not sure what the actual intention is.

1. there are two methods labeled with `@Get('{id}')`
2. The first of those methods has a parameter that just says `id: number` - should this be labeled with @Path?
3. `@Post` method has a parameter called `requestBody` and in the code refers to a variable called `request`; are these supposed to be the same thing?
4. second `@Get` method has a parameter called ID and the code refers to a variable called `id`; again, are these supposed to match?
5. Both of the `@Get` methods have parameters that they don't seem to use; is this intentional?

**Comment by dgreene1** [comment]
Issues 1 and 4 were fixed in https://github.com/lukeautry/tsoa/pull/408

To answer issue 2, I believe that the absence of the @Path decorator is there to demonstrate that you don’t need to use he decorator. I believe tsoa automatically infers that parameters of the route function are automatically path variables if not otherwise specified.

Issue 5: yes I think it was one of those things were we hoped people would understand that the usage of the variables is up to the developer filling out the rest of the business logic.

That being said, these things may not have been clear. So if you would like to add additional documentation, we would love to see a PR. But since https://github.com/lukeautry/tsoa/pull/408 solved most of your concerns, we’ll close this ticket.
