### ISSUE TITLE
The example Controller is invalid for swagger generation

### ISSUE THREAD

**Issue by danshapir** [lukeautry/tsoa#373]
Having two @Get('{id}') with different query parameters just don't work.
You get only the latter one generated in the swagger.yaml file.

Is this intended?
```
 @Route('Users')
   export class UsersController extends Controller {
    @Get('{id}')
    public async getUser(id: number, @Query() name: string): Promise<User> {
        return await new UserService().get(id);
    }

    @SuccessResponse('201', 'Created') // Custom success response
    @Post()
    public async createUser(@Body() requestBody: UserCreationRequest): Promise<void> {
        new UserService().create(request);
        this.setStatus(201); // set return status 201
        return Promise.resolve();
    }

    @Get('{id}')
    public async getPrivateUser(@Path('id') ID: number, @Header('Authorization') authorization: string): Promise<User> {
        return new UserService().get(id);
    }
}
```

**Comment by dgreene1** [comment]
@danshapir I just released version 2.4.4 and PR https://github.com/lukeautry/tsoa/pull/408 which contains a readme update that clarifies the issue you presented. Thank your for being a member of our community. I'd love to see more people using tsoa since it's such a useful product. If you wouldn't mind sharing with people on twitter, reddit, or [dev.to](https://dev.to)?

Also, there were a bunch of other enhancements. Check those out in: https://github.com/lukeautry/tsoa/releases/tag/v2.4.4
