### ISSUE TITLE
Using types from external modules

### ISSUE THREAD

**Issue by lucas-rudd** [lukeautry/tsoa#377]
So, I am trying to set up tsoa with my typescript project. This project utilizes AWS lambda. As such, I have a request body, as well as Lambda context that gets provided to my lambda.

Since the Lambda context does not need to be exposed to documentation, I'm ok with it being excluded from swagger docs.

However, when I attempt to ignore node_modules, tsoa complains
```
 Error: No matching model found for referenced type Context. 
```

However, when not ignoring the node_modules directory, I get the following error
```
Error: Multiple matching models found for referenced type Context;
```

(which, is true of course. Context is a very common interface name)

I've tried to do something like the following
```
import { 
  /** 
   * @tsoaModel
   **/
  Context 
} from 'aws-lambda';
```

since I do not need this model to be exposed in the swagger docs (AWS handles this internally), but this (not surprisingly) does not work.

Is there any way to expose some node_modules for use by tsoa without extending the interface directly and creating unnecessary code/files in my project?

**Comment by dgreene1** [comment]
Recommended solution:
* You should create your own type that has the same shape as AWS-lambda’s context
  * due to TypeScript’s structural subtyping abilities, it doesn’t matter if the name of the interface is different so long as the properties and values are the same. So just copy the Context interface instead of importing it. Yes, I realize that this is not what you want to do, but since interfaces are stripped out of the runtime code, this shouldn’t have a significant performance impact. And as far as documenting it in the Swagger YAML, it’s really important to API consumers to know what data contract they have to meet. Consumers don’t know about your internals just the surface area that the Swagger YAML describes
  * Furthermore, abstractions are really useful in software since they allow you to switch to a different product someday if you want. For instance you could move to Azure functions someday if you make an intermediary type.

Context: I’m only one of the maintainers so my opinion is not rule of law, but I think it would be dangerous for an API to have a contract that could change anytime one of it’s libraries changes. So I would vote that we don’t add a feature that allows external types to be used in the Swagger generation. @endor do we currently support this?

**Comment by lucas-rudd** [comment]
Sure, I understand that thought process, I just wanted to clarify something.

My controller does not need the consumer to pass in the Context. It only needs the consumer to know about the body structure, query params, etc. The Context is provided to my Controller by AWS when the lambda is invoked. So, I do _not_ need the Context to be in the documentation, but I do need it as an one argument (along with the body, queryparams, etc) of my Controller for use in the lambda. 

Ideally, I could have an annotation to exclude it altogether from tsoa instrumentation since it has no impact whatsoever on the consumer.

something like the following

```
public handler = async (@Body body: MyHandlerEventBody, @Internal context: Context) => { 
...
}
```

**Comment by dgreene1** [comment]
The solution is to not expose any interfaces from dependencies in your swagger/tsoa models. Basically, just make a copy of the interfaces you got from other libraries and use those instead. Trust me it will work ([see this explanation here on "structural subtyping" as to why this works](https://github.com/lukeautry/tsoa/issues/340#issuecomment-518229063)).

**Comment by dgreene1** [comment]
@lucas-rudd after reading more about your specific case of using serverless, you might want to look into libraries such as https://github.com/awslabs/aws-serverless-express that do the conversion of the serverless context stuff into the standard express server. Maybe that would allow you to only document the swagger information for your service and not the serverless wrapper stuff. It's just an idea.

**Comment by 0v3rst33r** [comment]
@lucas-rudd @dgreene1 apologies guys, I know that this is closed already.

Any further progress that any of you know about on this?  I am asking as I have been using `tsoa` for more than 2 years now in a production application (with `nodejs microservices`), and am finally prototyping some serverless architectures (using the `serverless framework` with `AWS` as the cloud provider) and if I can not get the Swagger documentation generated from code/decorators like I am used to, it will feel rather painful and pointless to handle it any other way.
