### ISSUE TITLE
Pre-commit hook running full test-suite is very slow

### ISSUE THREAD

**Issue by HoldYourWaffle** [lukeautry/tsoa#436]
https://github.com/lukeautry/tsoa/commit/2a9e76ebdd874772a1ec8c998c3242cd79fbfac8 added a pre-commit hook that invokes the full linter/test-suite setup. Although I can definitely understand the reason for this, it's not really helpful when I'm just trying out some stuff and need to quickly make a "checkpoint" commit or when I'm ammending/squashing previous commits using interactive rebase. Especially the full test-suite is too slow (and in my opinion most times unnecessary) in that case.

As said before I understand the reasoning for this, I just find it very annoying to work with. Would it maybe be possible to configure it in a way that only certain branches (like `master`) require this check before committing?

**Comment by dgreene1** [comment]
Right now that commit hook is the only thing that helps me as a maintainer for sure that PRs are actually passing when they’re submitted to us. If you’re looking for a way to save your changes, then I’d recommend using `git stash

**Comment by dgreene1** [comment]
Also, we have plans to have the unit tests run every time a PR is submitted. That should ease some pain.

Until then git stash should help you.

I’m closing this “issue” since there is nothing wrong with tsoa in regards to the husky hook. Moreover, this is a good and standard practice that you’ll see in many libraries.

**Comment by HoldYourWaffle** [comment]
I have never come across a library that runs it's full test-suite on every commit but that might just be me.

> Also, we have plans to have the unit tests run every time a PR is submitted. That should ease some pain.

This would be the best solution of course, most projects nowadays do this.

**Comment by HoldYourWaffle** [comment]
I also just remembered that you can [skip commit hooks](https://stackoverflow.com/questions/7230820/skip-git-commit-hooks) with `git commit --no-verify`, that saves a lot of trouble when ammending/squashing commits.

**Comment by dgreene1** [comment]
> I also just remembered that you can skip commit hooks with git commit --no-verify, that saves a lot of trouble when ammending/squashing commits.

If you want to do that, that's fine. But please do make sure to run the tests when you push your final commit. We've had many PRs that were merged under the belief that they were passing. However, once they were merged they broke every subsequent PR. If that happens, I'm much less likely to accept a PR from someone who has done that.

That's why I recommended `git stash` as a much safer option for everyone since it will save a local copy of your changes. There's even a keep option that allows to save the code and keep working.

> I have never come across a library that runs it's full test-suite on every commit but that might just be me.

Husky (which is what runs the tests on the commits for us) is used by 163,672 different repositories (as of today's count). So this is an extremely common practice.

**Comment by HoldYourWaffle** [comment]
> If you want to do that, that's fine. But please do make sure to run the tests when you push your final commit.

Of course! I'm impatient, not barbaric ;)

> Husky (which is what runs the tests on the commits for us) is used by 163,672 different repositories (as of today's count). So this is an extremely common practice.

Interesting... I wonder how many of those use it for preventing `push` rather than `commit` when tests are failing, which I know to be a common (and I suppose good) practice.

**Comment by dgreene1** [comment]
> Interesting... I wonder how many of those use it for preventing push rather than commit when tests are failing, which I know to be a common (and I suppose good) practice.

I used to use the `pre-push` hook but it doesn’t work with libraries since it creates an infinite loop when you run npm publish.

**Comment by HoldYourWaffle** [comment]
That sounds odd, why would it create an infinite loop?
