### ISSUE TITLE
Cannot find name 'Exclude'

### ISSUE THREAD

**Issue by myalban** [lukeautry/tsoa#469]
Hi,

After updating to latest version I go this error : node_modules/tsoa/dist/metadataGeneration/tsoa.d.ts(67,33): error TS2304: Cannot find name 'Exclude'.
node_modules/tsoa/node_modules/typescript/lib/typescript.d.ts(4913,20): error TS2304: Cannot find name 'unknown'.

Any help ?

Thanks,
best regards

**Comment by dgreene1** [comment]
@myalban next time can you please fill out the full issue report template? I notice that you've deleted a lot of helpful things such as
`Version of the library: <!-- insert that here -->`
`Version of NodeJS: <!-- insert that here -->`
`* Confirm you were using yarn not npm: [ ]`
Additionally the issue template asks that you show us your code so we can better understand your use case. So please add those if you don't mind since it will be helpful for contributors who are interested in helping you.

#### the exclude error

As for the answer to your question, `Exclude` is not currently supported. If you can share your code and your use case, then I can mark this issue as `Help Wanted`  so that contributors know that we're open to a PR. But until then we don't have enough information.

#### The unknown error

Your other problem where it can't find `unknown` is another potential enhancement which is documented in https://github.com/lukeautry/tsoa/issues/452. The current workaround is to use `any` since they're functionally equivalent in swagger. If you have questions about that, please bring them up in https://github.com/lukeautry/tsoa/issues/452

### Potential Workaround

Without seeing your code, it's not clear to me what the ideal workaround for the Exclude problem would be. But based off of my understanding of `Exclude<T,K>` I think the following might be a helpful workaround.

```ts
// the "exclude" way that doesn't work with tsoa
export type AllStringLiterals = "a" | "b" | "c" | "d";
export interface IPostBody {
    onlyBAndD: Exclude<AllStringLiterals, "a" | "c">;
}

//  the workaround
export type BAndD = "b" | "d";
export type AllStringLiterals = "a"  | "c" | BAndD;
export interface IPostBody {
    onlyBAndD: BAndD
}
```

**Comment by WoH** [comment]
Please feel free to try the 3.x beta releases for now, which include the required changes.
