### ISSUE TITLE
Unions are not documented/validated equivalent to Typescript

### ISSUE THREAD

**Issue by WoH** [lukeautry/tsoa#506]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
[See the playground](https://www.typescriptlang.org/play/index.html?ssl=21&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgJIBkIzAFQJ4AOKA3gFDIXIBucANgK4QCMAXMiPQLYBG0ANKQC+pUJFiIUqAErAA5gAtchEuUo0GEAExsOPaENIjw0eEjQBZYABMrtCPiLIylanUYBmHV15QBL9YwALF56UAaGYMrIAKIAHnCcBHYAqiDAAPYgyAC8aJjYDigAPhbWtvZRJdJyioUA3IYImQDOYMhQEM30tGBscQlJEKkZWbnOam7MbEx+ExrayJqzFAEQnsjuBkA)

It seems like TS allows all kinds of combinations for Unions of Aliases, Models and Object literals.

## Current Behavior

Tsoa currently is very strict about property checking, so it would only validate Unions if it exactly matches one of the schemas in the union.

## Possible Solution

Reduce strictness, get accept all properties of union members as allowed, regardless of combination.
Show this by documenting in OpenAPI as anyOf instead of oneOf.

## Context (Environment)
Version of the library: 2.x

## Breaking change?
Yes, 3.0 stuff here.

**Comment by WoH** [comment]
Well reopen with more details

**Comment by WoH** [comment]
@dgreene1 I have some questions related to excess properties. Is there any place we can privately chat? Sorry to ask here but I think trying to validate type aliases broke my brain yesterday.

**Comment by dgreene1** [comment]
> Tsoa currently is very strict about property checking, so it would only validate Unions if it exactly matches one of the schemas in the union.

This strictness is by design since it matches the definition of a union.

> Show this by documenting in OpenAPI as anyOf instead of oneOf.

That would be inaccurate since once you narrow a union, you it can no longer be one of the other types. See [this playground here](http://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgJIEFkG8CwAoZQ5EOAWwgC5kAiDagGnyOVIE90qQBXUgI2kZ4AvvnyhIsRClQAhbEyIlyVWjIYLCbGZx78ogkXjHho8JGgDC8gorKUaqC+pubWFnXwH5D+MKwAOKOgyAPJQVgC8aJgAPmhycY4A3KJ4MFwgCGDAAPYgyADmEGDBYRYAFACUVKXh1sxQxVxQ+bguzMR2KrLUGh1sHMgAjIIdRFpUAEyjYyxuVADMM4SGPngIeQDOYMiNm1wANjtRRSWh4VUpRnjAMMjle4dgAHRKKBEfDk6V9UQbIJscgcIM8DjkCg8IPsjs8Bs8wDkAMpgKCgCGVSpXZj-QHA0HgyHQl5aeFIlFoqqYvo4oEgsEQx4wtgWUnI1EgdFU4RAA).

In terms of the example in my playground, once you've narrows `ABOrC` to an `IC` it can't also be an `IB`. That's the swagger term should stay as `"oneOf"` not `"anyOf"`.

What you're describing in [your playground link](https://www.typescriptlang.org/play/index.html?ssl=21&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgJIBkIzAFQJ4AOKA3gFDIXIBucANgK4QCMAXMiPQLYBG0ANKQC+pUJFiIUqAErAA5gAtchEuUo0GEAExsOPaENIjw0eEjQBZYABMrtCPiLIylanUYBmHV15QBL9YwALF56UAaGYMrIAKIAHnCcBHYAqiDAAPYgyAC8aJjYDigAPhbWtvZRJdJyioUA3IYImQDOYMhQEM30tGBscQlJEKkZWbnOam7MbEx+ExrayJqzFAEQnsjuBkA) is a bug in TypeScript which is detailed here: https://github.com/microsoft/TypeScript/issues/20863

> @dgreene1 I have some questions related to excess properties. Is there any place we can privately chat? Sorry to ask here but I think trying to validate type aliases broke my brain yesterday so I'd like to bounce some ideas off of you.

I'm pretty busy this week (and probably for the next month) with my day job since I just took over leadership of a new team. And github is my preferred way to chat if that's okay?

**Comment by WoH** [comment]
> This strictness is by design since it matches the definition of a union.

I know, I think I am kinda responsible for that and I also remember a very similar discussion we had about this, so I guess I should explain myself a little bit here.

Let's say we have a type X = (A|B) & (C|D) with properties a, a2 on A, b on B, c on C and d on D.
If we were to validate that, possible combinations should be {a, c}, {a, d}, {b, c} and {b, d}.
Currently, our implementation would also allow { a, b, c } because while validation against (C|D) would report excess, we swallow that and instead check if any of the subSchemas allows a, which schema (A|B) does, so we pass it on.

The "valid" implementation would build 2 "model schemas" for both A|B and C|D. While this approach seems reasonable, it quickly increases in complexity: (A|B|C) & (D|E|F) & (G|H|I) already has 3^3 = 27 possible combinations.

I assumed we'd have to do this, then realized this is not at all how TS even acts, so I wanted to check if that's what we actually want.

**Comment by dgreene1** [comment]
Part of me thinks that it’s irresponsible of API developers to even expose unions and aggregates. Like, why wouldn’t people want to keep it simple for their API consumers.

I have similar feelings about Pick and Omit.

On other words, if I felt that it was acceptable to take this stance, I would say: Don’t create crazy combinations— if you do, TSOA won’t support them.

But maybe I’m just in a cranky mood today haha.

But I do think that we can draw a line somewhere.

And maybe that line is the combination of a union and an aggregate in the same alias?

**Comment by WoH** [comment]
I'll read this as: This is fine for 2.x (where it is hard to even create these combinations since Aliases are not fully supported).

However, since I went down the rabbit hole already: Are you fine with these strict checks in the future?

**Comment by dgreene1** [comment]
Can you show the tests first or something?

That way we could work backwards?

It doesn’t matter if the tests are passing or not.

Or if you still want help with writing the tests, I can help sometime towards the end of the month.

**Comment by WoH** [comment]
https://github.com/lukeautry/tsoa/pull/505/commits/b347d52d60bad583028bc468ad1187e430dac797

**Comment by dgreene1** [comment]
I can’t give it an in-depth review right now, but it looks like you’re on the right track. :)

**Comment by WoH** [comment]
> I can’t give it an in-depth review right now, but it looks like you’re on the right track. :)

I think I will just have to keep pushing onto this branch for LiteralTypes and others? Still no feedback from Luke, which is fine I guess, but not having a 3.x branch to push for an alpha release or some targetable goal is a bit demotivating.

**Comment by dgreene1** [comment]
> Still no feedback from Luke, which is fine I guess, but not having a 3.x branch to push for an alpha release or some targetable goal is a bit underwhelming.

@WoH made you a collaborator from what he’s told me.

> I think I will just have to keep pushing onto this branch for LiteralTypes and others?

Still would be great to have separate PRs but you’d have to tell me when you want to “call it done” for a particular set of features.

But I’m also okay with a mega PR. Ultimately it’s whatever serves you best and helps you get the code review you desire.

**Comment by WoH** [comment]
> Still would be great to have separate PRs but you’d have to tell me when you want to “call it done” for a particular set of features.

Since each of them require aliases, they'd just be on top of each other I fear, but I'll try.
Might have to ask you to filter by commits if it does not make sense though.

> @WoH made you a collaborator from what he’s told me.

I got the invitation a few h ago :confetti_ball:
