### ISSUE TITLE
Add specMergin option "exclusive"

### ISSUE THREAD

**Issue by EdsonAlcala** [lukeautry/tsoa#512]
## Add specMergin option "exclusive"

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* I confirm that I
  - [X ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

I'm trying to overwrite a Swagger definition in tsoa.json

As https://github.com/lukeautry/tsoa/blob/master/src/swagger/specGenerator2.ts#L50
shows, there are 2 modes, immediate which replaces the whole spec and recursive.

The problem is that recursive is merging and I would like to fully replace a certain definition only.

## Possible Solution

Would it be possible to add an 'exclusive' mode, that does the same as recursive mode but only takes the second values, in this case my custom spec values?

Thanks a lot !

**Comment by dgreene1** [comment]
There are a lot reasons why we would have to be hard-pressed to introduce a way to completely overwrite what tsoa produces. So before we entertain the idea of this feature, please share 2 things:
* the output that you're currently getting from tsoa
* the output that you wish you were getting

**Comment by EdsonAlcala** [comment]
My current tsoa.json contains for specMerging and spec the following:

```
"specMerging": "recursive",
"spec": {
     "definitions": {
                "ITemplate": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/ITemplateBase"
                        }
                  ]
             }
       }           
 }
```

So, I know that tsoa will generate ITemplateBase and ITemplate, so I want to overwrite ITemplate.

What tsoa is giving to me in the swagger.json is:

```
		"ITemplate": {
			"properties": {
				"version": {
					"type": "number",
					"format": "double"
				},
				"name": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"name"
			],
			"type": "object",
			"allOf": [
				{
					"$ref": "#/definitions/ITemplateBase"
				}
			]
		},
		"ITemplateBase": {
			"properties": {
				"version": {
					"type": "number",
					"format": "double"
				},
				"name": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"name"
			],
			"type": "object"
		},
```
As you notice, because recursive mode do a merge it is including the properties of ITemplateBase.

So, the output that I would like to get is:

```
		"ITemplate": {
			"allOf": [
				{
					"$ref": "#/definitions/ITemplateBase"
				}
			]
		},
		"ITemplateBase": {
			"properties": {
				"version": {
					"type": "number",
					"format": "double"
				},
				"name": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"name"
			],
			"type": "object"
		},
```

**Comment by dgreene1** [comment]
I believe that the Schema you’re expecting to have outputted will be exactly what you want once #429 is completed.

So I still dont think we need to allow manual overwriting when tsoa can and will soon produce the Schema you want from just the type information alone.

@WoH can you confirm how he would write this once aliases have been added to 

My assumption is that you would write the code as such:
```ts
export interface ITemplateBase {
  version: number
}

export type ITemplate = ITemplateBase;
```
Until then @EdsonAlcala I would recommend that (if  you absolutely must have this) that you write an NPM script that modified the YAML after the fact. This is very easy to do since tsoa can be used programmatically.

I want to stress that tsoa should not allow developers to get this wrong and override it themselves. Our design goals state that the Schema should be generated from the types, and if not possible by types then decorators, and if not possible by decorators then JSDocs. The Schema you’re asking for will be completely possible to produce in v3. Thank you for your patience as we continue working on it. :)

**Comment by WoH** [comment]
I'm not sure why this is not a case for `interface Template extends TemplateBase` which should avoid the need to override templates I assumed.

You can alias a type on the 3.x branch as you pointed out: `export type ITemplate = ITemplateBase;`

If you want to make a reference to type TemplateBase just to overwrite I guess that would be an approach, albeit I'd call it a workaround at best.

**Comment by dgreene1** [comment]
Yes I agree with @WoH.

**Comment by WoH** [comment]
I still like the proposal, I just think it shouldn't be necessary to reach for that here.

**Comment by dgreene1** [comment]
If added this functionality, we would have to ask every bug submitter if they tried to override the schema. It places a burden on the maintainers that I think is unwarranted since tsoa has multiple ways to represent the types that are being asked for.

**Comment by WoH** [comment]
Since there are implications on the validation here aswell, I do not think the idea has enough details to implement this, but I'd appreciate a way to override one definition we can't represent where the user may be able to fill in the details that one definition only.
For the bug templates, there could be a checkbox to confirm you're not overriding the generated spec.
