### ISSUE TITLE
TS2322 - Type '{ ... }' is not assignable to type 'ModelSchema'

### ISSUE THREAD

**Issue by benjamin-carl** [lukeautry/tsoa#566]
Hi tsoa Team,
hi to all others,

after moving the working and untouched code to a new environment transpiling with tsc fails with the following error:

```
src/app/routes.ts:11:3 - error TS2322: Type '{ "properties": { "status": { "dataType": "double"; "required": true; }; "message": { "dataType": "string"; "required": true; }; "headers": { "dataType": "nestedObjectLiteral"; "nestedProperties": {}; "required": true; }; "payload": { ...; }; }; "additionalProperties": true; }' is not assignable to type 'ModelSchema'.
  Property 'dataType' is missing in type '{ "properties": { "status": { "dataType": "double"; "required": true; }; "message": { "dataType": "string"; "required": true; }; "headers": { "dataType": "nestedObjectLiteral"; "nestedProperties": {}; "required": true; }; "payload": { ...; }; }; "additionalProperties": true; }' but required in type 'RefObjectModelSchema'.

11   "ModelResponseUser": {
     ~~~~~~~~~~~~~~~~~~~

  node_modules/tsoa/dist/routeGeneration/tsoa-route.d.ts:22:9
    22         dataType: 'refObject';
               ~~~~~~~~
    'dataType' is declared here.
  node_modules/tsoa/dist/routeGeneration/tsoa-route.d.ts:9:9
    9         [name: string]: ModelSchema;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from this index signature.

```
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
The code should transpile without the error TS2322 like in the other environment.

## Current Behavior
The code does not transpile.

## Possible Solution
I can't stay on the working environment and really need to migrate.

## Steps to Reproduce
-

## Context (Environment)
Version of the library: 2.5.12
Version of NodeJS: 12.14.1
* Confirm you were using yarn not npm: [ ] (I use npm in all environments - should this matter for this issue?)

## Detailed Description
The working environment:

- tsc = 3.7.3
- node = 10.15.3
- tsoa = 2.5.7

The new and broken environment:

- tsc = 3.7.5
- node = 12.14.1
- tsoa = 2.5.12

The code, the tsconfig.json and tsoa.json and ALL other files are untouched/unchanged.
I debugging this issue now for over 8h and really appreciate any help, hint and so on. 

Thank you.

**Comment by dgreene1** [comment]
I’m happy to help diagnose this issue with you but I can’t do it without seeing the TypeScript code. Please add that above to the issue. I’ll need to see the types and the routes that use the types.

**Comment by benjamin-carl** [comment]
Cool @dgreene1 - thank you. I will collect the required information for you and provide it in the next minutes. 

What I've found out so far is:

- going back to tsoa 2.1.8 while everyrthing else (code: same, node: 12.14.1 and tsc: 3.7.5) stays the same will transpile fine - in the new environment! So just going back to 2.1.8 will fix it.

The report above contains one misleading information. The installed version was 2.5.7 in local node modules but 2.1.8 global. I have not checked the global installation. BTW: v2.1.8 reports itself as 0.3.0 which was also a bit misleading while debugging (in package.json the version is correct).

I will try now which younger version it breaks.

**Comment by benjamin-carl** [comment]
Hi @dgreene1 

I digged a bit deeper and so it seems currently being more a layer 8 problem than a bug.

When I switch from 2.1.8 to 2.2.0 where it breaks the first time ...

```
src/app/routes.ts:255:36 - error TS2538: Type 'string[]' cannot be used as an index type.

255           TypeAuthenticationMethod[secMethod.name],

```

So I need to migrate the code - my assumption was that it would not break when switching from 2.1.8 directly to v2.5.7||v2.5.7.

Do you have a migration guide from version to breaking version? So for example from 2.1.8 to 2.2.0? There are changes in the `interface Security` and currently I dont know if there are some more changes which I have not found yet.

**Comment by dgreene1** [comment]
We started adding migration guides / deprecation notices pretty recently (when I took over as maintainer). The version you were on is way older than when I started on tsoa.

As I mentioned, I can assist you further if you provide the full files for your types/interfaces and the full files for your routes.

**Comment by gavinvangent** [comment]
I came across this a few days ago too. The problem was a result of the output from the route template that gets generated when running `tsoa routes`

I'm using a custom template, and I'm assuming you are too. You can change the `tsoa.json` file; if `middlewareTemplate` is set under `routes`, you have a custom template.

The change I made was to add the `dataTypes` to the `TsoaRoute.Models` declaration:

before:
```
const models: TsoaRoute.Models = {
    {{#each models}}
    "{{@key}}": {
        {{#if enums}}
        "enums": {{{json enums}}},
        {{/if}}
        {{#if properties}}
        "properties": {
            {{#each properties}}
            "{{@key}}": {{{json this}}},
            {{/each}}
        }
        {{/if}}
    },
    {{/each}}
};
```

after:
```
const models: TsoaRoute.Models = {
    {{#each models}}
    "{{@key}}": {
        {{#if enums}}
        "dataType": "refEnum",
        "enums": {{{json enums}}},
        {{/if}}
        {{#if properties}}
        "dataType": "refObject",
        "properties": {
            {{#each properties}}
            "{{@key}}": {{{json this}}},
            {{/each}}
        }
        {{/if}}
    },
    {{/each}}
};
```

**Comment by dgreene1** [comment]
We’ve made so many advancements in tsoa and many of those are incompatible with custom templates. In fact, we recently added a warning to the readme about how using a custom template is a “proceed at your own risk” kind of situation.

Would you please consider coming back into the real codebase?

We’d be better able to assist you then.

And if there’s something that your custom template provides that we don’t (which I doubt at this point), we will simply add it in for you. :)

**Comment by gavinvangent** [comment]
Hi @dgreene1 

I am using a custom template because I was not happy with either `inversify-js`, nor `typescript-ioc` and prefer the less invasive approach that `awilix` has taken. Unfortunately, `tsoa` doesn't have a default integration for awilix (yet). Is there a roadmap for awilix?

In short, I don't like:
- `inversify-js` because of the amount of boilerplate code and decorators floating around in the code, making it hard to understand at a glance
- `typescript-ioc` because it creates a global container that exposes all bound types/classes to everything by wrapping the constructor functions of all bound types/classes. This means you need to have a good understanding of the quirks of the framework before being able to contribute, and even then, you need to remain cognitive of all the code and whether they are singletons/scoped/etc before just constructing new instances.

I could elaborate further, but I'm sure you understand the pro's and con's of these frameworks and  you don't need me to explain further?

Awilix doesn't invade all your classes/types and is only really used to glue everything together at start up. After that, you can forget about awilix, unless you need to resolve instances from the container, in which case, the container needs to be passed around, or resolver functions can be added to the container so that the resolvers can be injected into the classes that need them.

Again, I can elaborate further on request.

**Comment by dgreene1** [comment]
Actually @gavinvangent I’m not familiar with any TS IOC libraries. I’ve only used DI in angular 1 and C#. Anyway, please create a new issue and maybe you can explain it there so a noob like me can pick it up haha.

**Comment by benjamin-carl** [comment]
> I came across this a few days ago too. The problem was a result of the output from the route template that gets generated when running `tsoa routes`
> 
> I'm using a custom template, and I'm assuming you are too. You can check the `tsoa.json` file; if `middlewareTemplate` is set under `routes`, you have a custom template.
> 
> The change I made was to add the `dataTypes` to the `TsoaRoute.Models` declaration:
> 
> before:
> 
> ```
> const models: TsoaRoute.Models = {
>     {{#each models}}
>     "{{@key}}": {
>         {{#if enums}}
>         "enums": {{{json enums}}},
>         {{/if}}
>         {{#if properties}}
>         "properties": {
>             {{#each properties}}
>             "{{@key}}": {{{json this}}},
>             {{/each}}
>         }
>         {{/if}}
>     },
>     {{/each}}
> };
> ```
> 
> after:
> 
> ```
> const models: TsoaRoute.Models = {
>     {{#each models}}
>     "{{@key}}": {
>         {{#if enums}}
>         "dataType": "refEnum",
>         "enums": {{{json enums}}},
>         {{/if}}
>         {{#if properties}}
>         "dataType": "refObject",
>         "properties": {
>             {{#each properties}}
>             "{{@key}}": {{{json this}}},
>             {{/each}}
>         }
>         {{/if}}
>     },
>     {{/each}}
> };
> ```

Hi @gavinvangent 

that was the required "fix" - I just copy pasted it and did no further check on the change itself. I'm using a custom template. Currently not really sure if I need it. I'm not using IoC within the template and use the hardcoded way. I will change it in the next weeks to make use of IoC - and I'm using Awilix and would also like to have "native" support for Awilix. For the same reasons like @gavinvangent .

@dgreene1 thanks for your support so far. I'm on the latest 2.x release and everything is working (currently adding OAS 3 specific stuff) and think we can close this issue.

**Comment by gavinvangent** [comment]
@dgreene1 As soon as I find time, I'll write up a new issue requesting Awilix and add some insight into how best to implement it, along with information on why I believe Awilix trumps the other two IoCs. I'm happy to contribute towards an Awilix feature branch should tsoa want to add Awilix support 👍

**Comment by WoH** [comment]
We use a custom module to create the controllers and wrap it into a custom ioc module that exposes an API the default templates can work with, maybe you can wrap Awilix in a similar manner?

If you set the `iocModule` in the config, you can export an object which provides a function with this signature: 

```
  public get<_T>(controller: Function): any {
    return controllerInstance;
  }
```

tsoa will call the `get()` function on this exported object with the class definition as a parameter and expects an instance as the return parameter.

**Comment by gavinvangent** [comment]
I don't mean to barge my way in and completely redirect the progress tsoa is making, and this is probably not the right forum for this, but I've added some context to what I was referring to above along with some suggestions. If there is a better place to take this discussion, please let me know. Again, I hope to make it known that I'm not trying to impose myself on your library. I'm no expert with `tsoa` and haven't delved deep into the underlying code. I'm merely here to share some of my thoughts :) 

@WoH Agreed, it could be as simple as that however I don't feel this is practical or as good as it could be, no disrespect.

I mainly dislike the iocModule because I don't want to define my ioc container in a file that can then be imported from anywhere (just add `import * as container from './ioc/containerts'` or similar, and boom you now have my container). This means you now have access to my db connection, authentication services, etc. There are ways around this which are not described in the README.md, meaning some people who are copy/pasting the code from the README.md may not be aware of the risks. I'd suggest moving away from this approach, and find another way to have the container injected; more specifically, inject a function that can purely resolve controllers.)

I'd suggest changing this definition in the handlebars template:
```ts
export function RegisterRoutes(app: express.Express) {
...
}
```
to something like:
```ts
export function RegisterRoutes(options: RegisterRoutesOptions) {
...
}

export interface RegisterRoutesOptions {
  app: express.Express, // required
  controllerResolver?: <T extends Controller = any>(name: string) => T, // Notice it is optional for those that dont what to use an ioc implementation
  authentication?: (request: express.Request, securityName: string, scopes?: string[]): Promise<any>, // again, optional
  // anything else you may need in future versions of tsoa
}
```

This gives you:
- flexibility to extend the `RegisterRoutes` function + template for future changes/improvements
- removes the need to add a iocModule specific file and then defining an iocModule in the `tsoa.json` 

Since the user has to invoke `RegisterRoutes` at some point during the start up cycle, its now more obvious whats being supplied to `tsoa`; by that i mean:

Rather than having multiple files defining how I use `tsoa` (`tsoa.json`, `index.ts`, `ioc-module.ts`, `authentication.ts`, etc), I would rather see this (personal opinion, may be subjective):
```ts
// index.ts
const container = awailix.createContainer(...); // awilix
// or
const container = new inverifyJs.Container();
// or
const container = typescriptIoc.Container;

// Now register all your components with your container that you need, like services, providers, etc

const controllerResolver = (name: string) => {
  const controller = container.resolve<Controller>(name); // awilix specific here, apply specific logic to whichever ioc library you use.

 if (controller instanceof Controller) {
   return controller;
 }

  throw new Error('Not found');
};

const authentication = .......
const app = getExpressAppSomehow(....);

RegisterRoutes({
  app,
  controllerResolver,
  authentication,
  // any other variables that may be required in future
});

app.listen(3000);
```

I understand that this is a breaking change so that introduces complications of its own, but might be something worth considering, sooner rather than later.

To start the transition (should you choose to move in this direction), the RegisterRoutes could be defined as:
```ts
export function RegisterRoutes(options: express.Express | RegisterRoutesOptions) {
  // check if options is an express object or an options object
...
}
```

The other thing I want to suggest is splitting the template up into smaller templates with a main wrapper template to compose it all, using handlebar's partial template loading.

Without going into too much detail, I envision the main file `layout.hbs` file having a similar structure:

```hbs
// layout.hbs
{{> imports }}

export function RegisterRoutes(options: RegisterRoutesOptions) {
  {{> initial }}
  {{> preRequestHandlers }}
  {{> requestHandlers }}
  {{> postRequestHandlers }}
  {{> final }}
}
```

Now you can move the routing logic to `requestHandlers.hbs`:
```hbs
{{#each controllers}}
    {{#each actions}}
        app.{{method}}('{{fullPath}}',
            {{#if security.length}}
            authenticateMiddleware({{json security}}),
            {{/if}}
            function (request: any, response: any, next: any) {
            const args = {
                {{#each parameters}}
                    {{@key}}: {{{json this}}},
                {{/each}}
            };

            // WARNING: This file was auto-generated with tsoa. Please do not modify it. Re-run tsoa to re-generate this file: https://github.com/lukeautry/tsoa

            let validatedArgs: any[] = [];
            try {
                validatedArgs = getValidatedArgs(args, request);
            } catch (err) {
                return next(err);
            }

            {{#if ../../iocModule}}
            const controller: any = iocContainer.get<{{../name}}>({{../name}});
            if (typeof controller['setStatus'] === 'function') {
                controller.setStatus(undefined);
            }
            {{else}}
            const controller = new {{../name}}();
            {{/if}}


            const promise = controller.{{name}}.apply(controller, validatedArgs as any);
            promiseHandler(controller, promise, response, next);
        });
        // WARNING: This file was auto-generated with tsoa. Please do not modify it. Re-run tsoa to re-generate this file: https://github.com/lukeautry/tsoa
    {{/each}}
    {{/each}}
```

Side note - we'd need to change the iocModule logic in the `routeHandlers.hbs`:
```hbs
// old
            {{#if ../../iocModule}}
            const controller: any = iocContainer.get<{{../name}}>({{../name}});
            if (typeof controller['setStatus'] === 'function') {
                controller.setStatus(undefined);
            }
            {{else}}
            const controller = new {{../name}}();
            {{/if}}

// new
            let controller: Controller;
            if (options && options.controllerResolver) {
                controller: Controller = options.controllerResolver({{../name}});
                if (typeof controller['setStatus'] === 'function') {
                  controller.setStatus(undefined);
                }
            } else {
                controller = new {{../name}}();
            }
```

Back to partial templates - Then a file like `postRequestHandlers.hbs` might look like this:
```hbs
// postRequestHandlers.hbs
  {{> security }}
  {{> boilerplate }}
  {{> validations }}
```

This makes the template composible, and allows the consumer to override smaller parts of the default template rather than having to completely replace the base template and then having to try keep his/her whole template up to date with the base template when upgrading to newer versions of `tsoa`.

For example, the user could then add their own `security.hbs` file which is then rendered rather than the `default/base security.hbs` file while everything else remains default.

I'd like to hear your thoughts @dgreene1 @WoH  :)

**Comment by dgreene1** [comment]
My preference would honestly be to remove the ability to add custom templates since it’s an enormous maintenance headache. But I don’t plan on suggesting that since many people use it. But those that do are basically at risk of having their contract broken at any time.

As for IOC, I have never needed it since Jest allows me to provide runtime substitution at any time. So there’s no reason to invert control since the ES module loading system does that by default.

I’m open to finding a non handlebars solution to enabling IOC generically for tsoa.

Perhaps the best way to start is for you to link to an example repository so we can learn more about your usage.
