### ISSUE TITLE
Support for more than one decorator per function

### ISSUE THREAD

**Issue by lucas-rudd** [lukeautry/tsoa#579]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

There are use-cases where an endpoint can be mapped to more than one HTTP method. For example, in the case of a UPSERT functionality when utilizing a database like MonoDB, the same endpoint to create or update a model could be used, with the only differences being optional query parameters, like so
```ts
public async putModel(model: Model): Promise<Model> {
        try {
            await this.db.init();
            console.log(`attempting to create/modify the model ${pokerPlayer}`);
            return await Model.findOneAndUpdate(
                { _id: model._id },
                { $set: model },
                {
                    new: true,
                    upsert: true
                }
            );
        } catch (err) {
            console.log(err);
            throw err;
        }
    }
```

In this use-case, you may chose to have the controller look like so
```ts
@Put('model')
@Post('model')
@Patch('model')
@Response<Model>('201', 'Model created')
@Response<Error>('400', 'Bad Request')
@Response<Error>('500', 'Default Error')
    public async putModel(@Body() body: Moodel): Promise<Model> {
        if (!body || Object.keys(body).length === 0) {
            throw new Error('Must specify a request body');
        }
        const responseModel = await this.modelService.putModel(body);
        console.log(`model created`);
        return responseModel;
    }
```
 

## Current Behavior

The current behavior is that tsoa throws the following error
```
Only one path decorator in 'function () {
        var methodId = this.node.name;
        var controllerId = this.node.parent.name;
        return controllerId.text + "." + methodId.text;
    }' method, Found: Put, Post, Patch Error: Only one path decorator in 'function () {
```

## Possible Solution

A possible solution would be to generate a Swagger documentation for each annotation on the method unless there are duplicates (i.e. if there are 2 `@Post` annotations) 

## Steps to Reproduce

1. create a controller
2. annotate with two annotations (doesn't matter which)
3. run tsoa swagger generation

## Context (Environment)
Version of the library: 2.5.13
Version of NodeJS: v10.15.3
* Confirm you were using yarn not npm: [X]

## Detailed Description

Suggesting allowing for multiple annotations, as long as there are no duplicates. This will generate a swagger path for each annotation, i.e. one for POST, one for PATCH, and one for PUT.

## Breaking change?

No.

**Comment by dgreene1** [comment]
Removing this validation would prevent a host of easily catchable “copy and paste” errors.

In fact, that particular check helps me when I’m quickly building out an API.

The workaround is pretty easy too: Just have each route call the same function.

I’ll leave this open so other people can comment but it’s my belief that this should be marked as “will not fix” due to the reasons I stated above. I’ll remove the label of this feature is popular.

**Comment by lucas-rudd** [comment]
That's fair.

I don't agree, but I do see your perspective.
Regardless, thanks for the quick response. I've done the workaround; it's not difficult, and it's probably a better practice anyway to have a controller per HTTP method, even if they just call the same method so that they can more easily be altered if necessary. 

There are just some use-cases where I think it's appropriate to map several HTTP methods (mainly things like PUT, POST, and PATCH for certain DB setups).

**Comment by dgreene1** [comment]
I just wanted to add that there are many reasons why the schema for these different calls would be different. So the premise that you could share the same function is not quite accurate. Here are a couple of reasons:

1.  The body for a PUT and PATCH should probably be substantially different due to the fact that a PUT will overwrite the entire resource and a PATCH is designed to overwrite only the provided parameters. So while a PUT body might be of type `IUser`, a Patch body should be either `Partial<IUser>` or be some implementation of [the JSON Patch spec](http://jsonpatch.com/).
1.  While a PUT takes a full object (including the ID), a POST body shouldn't include the ID of the object since that would be generated by the server.
1.  a DELETE typically wouldn't have a response body at all
1.  a GET almost never includes a request body

So after thinking about it the workaround is actually the recommended solution:

> Just have each route call the same function

**Comment by Muratcol** [comment]
Any update about this topic? Workaround works, yes, but in that way, more than one same method occurs in swagger. Ofc, this is what is expected, but if only one method is visible in swagger, but the controller supports more than one method, I think it would be more useful.
