### ISSUE TITLE
Add support for @Hidden() decorator on Query Parameters

### ISSUE THREAD

**Issue by gdspicer58** [lukeautry/tsoa#582]
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

A developer should be able to hide a specific query parameter that they may not want the general public to know about but still need from their UI. Example:

The generated swagger would not show anything for `superSecretFlag`

```ts
export class SampleController {
  @Get('id')
  public async find(@Path('id') id:string, @Hidden() superSecretFlag: boolean = false): Promise<any> {  }
}
```

## Current Behavior

Adding Hidden next to a parameter does not seem to do anything

## Context (Environment)
Version of the library: 2.3.8
Version of NodeJS: 10.16.3
* Confirm you were using yarn not npm: [X]

**Comment by dgreene1** [comment]
I'm unaware of how we could change the swagger JSON/YAML that is created so that Swagger UI (a different product) knows to not show that element. So I believe our only choice is to remove it from the swagger JSON/YAML that is created. That means that the specific parameter won't be available if someone wants to create an auto-generated client.

So is that what you're looking for?

If so, I think we could only allow the @Hidden decorator to be used on an optional parameter. Otherwise you'd get into a situation where the call would always return a Bad Request status code and the UI wouldn't be able to give you feedback about why you're getting an error.

Please confirm your expectations.

**Comment by gdspicer58** [comment]
Since the variable corresponds to a query parameter, if it isn't supplied, it defaults to a value, so it is an optional parameter for our purposes. In that case, I think removing it from the JSON/YAML created will work.

Otherwise, I've seen requests for "categorizing" certain variables, controllers or functions (for example if a company wanted an internal facing swagger doc and an external facing swagger doc). If these optional query parameters could also be thrown in with that request, that would also work, but I would argue that would be a separate feature request.

Either way that makes the behavior I'm looking for possible.

**Comment by dgreene1** [comment]
Okay,  I'll mark this as ready to be worked now that we agree that the acceptance criteria would involve (a) tsoa generation failing if the parameter is on a non-optional parameter and (b) that the parameter would not be present in the output of the generated swagger JSON/YAML.

P.S. we'd also take a PR from you @gdspicer58 if you're interested. This is an easy to moderately easy PR. I'd do it myself if it wasn't crunch time at work.
