### ISSUE TITLE
External depdency blacklisting

### ISSUE THREAD

**Issue by timstableford** [lukeautry/tsoa#588]
## Sorting

* **I'm submitting a ...**
  - [x] bug report
  - [x] feature request
  - [x] support request

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

(Apologies for x'ing all 3 but it's kind of all of them)

## Current Behavior
Currently this framework doesn't allow including type definitions from the node_modules folder. I'm not sure I agree with this, but perhaps that's because I don't see a way forward with the program I'd like to port to this framework.

## Expected Behavior
The architecture I'm working on is currently split into 3 relevant pieces, a server-side in TypeScript, a client web application in Angular/TypeScript and a shared library of type definitions that are used by both sides. I'd like to be able use those common typings in tsoa, but because my internal common typings package falls into the external dependency category this framework can't use them without cp hackery. I'd expect to be able to use those common typings.

So I'm not sure if it's a bug that this wasn't considered, a lack of support leading to it being cut-out or just me not understanding the framework.

#377 hints that searching through all of the modules would be too slow, but could it be possible to follow import statements?

**Comment by dgreene1** [comment]
We have to keep the build process quick since it’s already pretty slow. The expected workaround is to create interfaces inside of the server application that have the same data. I.e just copy and paste them into your server side application. Then when you take the request body type and try to pass it to a function that uses your types from bode modules it will still work due to the way TypeScript’s structural subtyping works.

This is all explained in the readme: https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD
