### ISSUE TITLE
tsoa3 OpenAPI3 spec: regression for string literal types?

### ISSUE THREAD

**Issue by jayp** [lukeautry/tsoa#708]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior

I have a string literal type like this:

```ts
export type DayOfTheWeek =
  | 'Sunday'
  | 'Monday'
  | 'Tuesday'
  | 'Wednesday'
  | 'Thursday'
  | 'Friday'
  | 'Saturday'
```

`tsoa3` generates a OpenAPI3 spec related to the above as:

```json
{
  "schemas": {
    "DayOfTheWeek": {
      "anyOf": [
        {
          "type": "string",
          "enum": ["Sunday"],
          "nullable": false
        },
        {
          "type": "string",
          "enum": ["Monday"],
          "nullable": false
        },
        {
          "type": "string",
          "enum": ["Tuesday"],
          "nullable": false
        },
        ...
      ]
    }
  }
}
```

My client generator (openapi-generator, typescript-axios variant) borks on this:

```
[main] WARN  o.o.codegen.DefaultCodegen - DayOfTheWeek (anyOf schema) already has `string` defined and therefore it's skipped.
```

It seems v2.5 might have been generating a spec that the generator was able to handle. Older spec looked like this:

```json
"type": "string",
"enum": [
   "Sunday",
   "Monday",
   "Tuesday",
   ...
]					]
```

This might not be tsoa's issue, and maybe it is more on `openapi-generator`. But the spec generated seems a bit dubious to me.  It seems to be doing enum a level below I expected. Wanted to know if this is (1) expected, (2) regression, (3) something else?

PS: As you can guess, I am not deep expert on OpenAPI spec. Just trying to figure things out by reading docs here and there.

**Comment by WoH** [comment]
tsoa used to only support string literal unions. When I introduces Unions, string literal unions used to be a special case in the type resolver, which I removed for v3 because the code was very fragile.
The produced OAS is valid, but not what a human would probably write.

The behavior is expected, but I've seen that this also causes i.e. SwaggerUI to validate correctly but not display a dropdown of the string enums any more.

The best way to improve the current bahavior would probably be to collect the string/number/boolean schemas and merge them into one big enum respectively.

Ref for OpenAPI 3: https://github.com/lukeautry/tsoa/blob/master/src/swagger/specGenerator3.ts#L434

**Comment by jayp** [comment]
Ok, let me take a stab at this. Without fixing this, I'm afraid I'll be stuck on tsoa2. Either I fix this or I fix my client generator. lol.

I looked at definitions.spec.ts for unit tests, is the test related to `specLiteralVal` the one to hone in on first?

**Comment by fantapop** [comment]
It would be great to get this one fixed.  @jayp did you end up putting time toward this?

**Comment by gdspicer58** [comment]
+1, ran into this issue today. Thank you @fantapop for working on it.

**Comment by jayp** [comment]
Yay @fantapop - I hadn't. So I am super glad you did. Sorry didn't respond to your ask earlier.
