### ISSUE TITLE
please support string literal type

### ISSUE THREAD

**Issue by kahirokunn** [lukeautry/tsoa#882]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

**Comment by WoH** [comment]
String literally are supported, please fill out the full template or try to provide that information in a reproducible form or they will be closed.

**Comment by WoH** [comment]
Template Literal Types were added in #799

**Comment by u12206050** [comment]
Hmm, doesn't seem to work for me though :)

Getting this error:
```
Generate routes error.
 Error: Could not the type of `${number}`

```

**Comment by WoH** [comment]
The sanity test currently in place is that it can be represented as a string enum (with a limit, i.e. the Compiler eventually gives up at a certain number), otherwise, like in your example, you can just type it as `string`.

Maybe a good idea would be to 
a) fix the error message, since I clearly can't be trusted with forming proper sentences
b) bail out to as string type

That said, I can't imagine that this was the intention of the original author was when he opened this ticket, as thin on information as it is.

**Comment by benrosen-moodys** [comment]
```typescript
type WithoutExtendedStringTypes<T extends unknown> = T extends string
  ? string
  : T extends Array<infer U>
  ? WithoutExtendedStringTypes<U>[]
  : T extends Record<string, any>
  ? { [key in keyof T]: WithoutExtendedStringTypes<T[key]> }
  : T;
```

This type will downgrade template literal string types to regular string types. Here's an example:

``` typescript
type ExtendedStringType = `${string}-${string}-${string}-${string}-${string}`;

type ObjectWithExtendedStringTypes = {
  foo: ExtendedStringType;
  bar: {
    baz: [ExtendedStringType, ExtendedStringType];
  };
};

const withExtendedStringTypes: ObjectWithExtendedStringTypes = {
  foo: "a-a-a-a-a",
  bar: {
    baz: ["b-b-b-b-b", "c-c-c-c-c"],
  },
};

const withoutExtendedStringTypes: WithoutExtendedStringTypes<ObjectWithExtendedStringTypes> =
  {
    foo: "foo",
    bar: {
      baz: ["bar", "baz"],
    },
  };
```
You can wrap your types with `WithoutExtendedStringTypes` when you give them to TSOA.
