### ISSUE TITLE
Export models in routes

### ISSUE THREAD

**Issue by andreasrueedlinger** [lukeautry/tsoa#90]
Currently when building the routes file all the models are resolved by `tsoa`. It would be very nice if this generated models object would be exported.

Use case: You load some data from database but only want to send the properties defined in the interface of the return type of a route. In this case you need a way to dynamically "copy" only the properties of the interface and return this "stripped" object.

Or has anyone a better idea how to achieve the goal above? Only select the properties needed in the query to the database is not easier since I want the interface to be the "master" and changing the interface automatically would change the set of returned properties.

**Comment by dgreene1** [comment]
I believe this is solved now by using the `keyof T` feature that TypeScript added. So you don't need tsoa to accomplish this.

```ts
interface IDatabaseModel {
    aProperty: string;
    anotherProperty: string;
}

const recordOfDbProperties: Record<keyof IDatabaseModel, true> = {
    aProperty: true,
    anotherProperty: true
};

const strippedProperties = Object.keys(recordOfDbProperties);

console.log(strippedProperties); // outputs (2) ["aProperty", "anotherProperty"]
```

That should either solve your problem or it should help you find your way; but unfortunately this issue is from 2017, I'm going to close it for housekeeping purposes. Thank you for using tsoa and please tell your friends! :)
