### ISSUE TITLE
Sort swagger controllers routes by method and not by path 

### ISSUE THREAD

**Issue by demarchenac-nativapps** [lukeautry/tsoa#931]
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Detailed Description

Hi! I want to know if it is possible to sort the generated routes by methods  like [GET, POST, PUT, DELETE] instead of these being generated by their path.

### Current route generation:
![image](https://user-images.githubusercontent.com/61156609/110008092-54fca600-7ce9-11eb-8767-b2a242694186.png)

### Desired route generation:
![image](https://user-images.githubusercontent.com/61156609/110008182-6a71d000-7ce9-11eb-8443-a3204c1be6fe.png)

**Comment by WoH** [comment]
Currently, the best way to do this is to use `generateSpec` and post-process the OpenAPI spec there.

**Comment by demarchenac-nativapps** [comment]
Could you ellaborate or give some insight?

**Comment by WoH** [comment]
We don't guarantee any particular order in the generated spec. If we were to, I would not suggest ordering based on the HTTP method, as the OpenAPI spec dictates a hierarchy: .paths[/${path}].{method}, meaning the path comes first and iirc has to be unique, even with regard to the placeholders (can't have /hi/{id} and /hi/{otherId}).

My initial thought was to take the OpenAPI spec, which is just a big json object and post-process this json based on your personal flavour to trick your Doc generator into rendering based on these preferences, but even there, this may not be possible due to the hierarchy required by OpenAPI, leaving only the option to ask SwUI to change the visual representation of the spec.
