### ISSUE TITLE
Endpoint versioning

### ISSUE THREAD

**Issue by zxxc** [lukeautry/tsoa#950]
Some of our endpoints support different version from the header parameter
for example, a client app will send a request with
`x-supported-version: 1.1 // or 1.2`

and we invoice different functions with different request validators

Is it possible to achieve something like this with tsoa?
```
@Route('/public')
export class AccountsController extends Controller {

  @Get("accounts")
  @IsApplicable(@Header('x-version') version, '1.1')
  public async getAccounts1(
    @Header('x-account-id') account_id: string
  ): Promise<AccountsGetResponse> {
return await service.getAccounts(account_id)
  }

  @Get("accounts")
  @IsApplicable(@Header('x-version') version, '1.2')
  public async getAccounts2(
    @Header('x-account-id') account_id: string,
    @Header('x-user-id') user_id: string
  ): Promise<AccountsGetResponse> {
           return await userService.getUsers(user_id).getAccounts(account_id);
  }
}

**Comment by WoH** [comment]
How would you like to express this in OpenAPI?

**Comment by Sawtaytoes** [comment]
I was wondering about the same thing.

In the past, I worked with someone who really knew what he was doing with C# and has a Swagger API built with the API version in the header rather than the URL.

I'm not familiar with Swagger myself which is why I chose to use tsoa in the first place.

What's your recommendation on API versioning?

1. `/v1/...`
2. `/user/v1` includes `/user/v1/:userId`
3. ???
